name: docker

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
    tags:
      - '*'
env:
  DOCKER_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:${{ github.ref_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Prepare source and patch
        run:  sh patch.sh
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: llvm-mingw
          push: true
          tags: ${{ env.DOCKER_REPO }}
        env:
          SOURCE_DATE_EPOCH: 0
